# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ui.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ui.proto',
  package='ui',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08ui.proto\x12\x02ui\"-\n\x13\x43ontrollerStatusCmd\x12\x16\n\x03\x63md\x18\x01 \x01(\x0e\x32\t.ui.UiCmd\"\xa7\x01\n\x14\x43ontrollerStatusResp\x12#\n\x06status\x18\x01 \x01(\x0e\x32\x13.ui.StatusCmdStatus\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\r\n\x05\x63Time\x18\x04 \x01(\t\x12\x0c\n\x04mode\x18\x05 \x01(\t\x12\x0f\n\x07program\x18\x06 \x01(\t\x12\x0e\n\x06inputs\x18\x07 \x01(\t\x12\x0f\n\x07outputs\x18\x08 \x01(\t\"G\n\x14SetControllerModeCmd\x12\x1e\n\x03\x63md\x18\x01 \x01(\x0e\x32\x11.ui.UiModeControl\x12\x0f\n\x07reqMode\x18\x02 \x01(\t\"Z\n\x15SetControllerModeResp\x12 \n\x06status\x18\x01 \x01(\x0e\x32\x10.ui.UiModeStatus\x12\x0f\n\x07setMode\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t*\'\n\x05UiCmd\x12\n\n\x06U_NONE\x10\x00\x12\x12\n\x0eU_CNTRL_STATUS\x10\x01*[\n\x0fStatusCmdStatus\x12\x0b\n\x07US_NONE\x10\x00\x12\x0b\n\x07US_GOOD\x10\x01\x12\x15\n\x11US_UNEXPECTED_CMD\x10\x62\x12\x17\n\x13US_SERVER_EXCEPTION\x10\x63*+\n\rUiModeControl\x12\n\n\x06\x43_NONE\x10\x00\x12\x0e\n\nC_SET_MODE\x10\x01*z\n\x0cUiModeStatus\x12\x0b\n\x07\x43S_NONE\x10\x00\x12\x0b\n\x07\x43S_GOOD\x10\x01\x12\x0e\n\nCS_MODE_NA\x10\x02\x12\x10\n\x0c\x43S_MODE_FAIL\x10\x03\x12\x15\n\x11\x43S_UNEXPECTED_CMD\x10\x62\x12\x17\n\x13\x43S_SERVER_EXCEPTION\x10\x63\x32X\n\nUiMessages\x12J\n\x13GetControllerStatus\x12\x17.ui.ControllerStatusCmd\x1a\x18.ui.ControllerStatusResp\"\x00\x32[\n\rUiControlMode\x12J\n\x11SetControllerMode\x12\x18.ui.SetControllerModeCmd\x1a\x19.ui.SetControllerModeResp\"\x00\x62\x06proto3'
)

_UICMD = _descriptor.EnumDescriptor(
  name='UiCmd',
  full_name='ui.UiCmd',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='U_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='U_CNTRL_STATUS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=398,
  serialized_end=437,
)
_sym_db.RegisterEnumDescriptor(_UICMD)

UiCmd = enum_type_wrapper.EnumTypeWrapper(_UICMD)
_STATUSCMDSTATUS = _descriptor.EnumDescriptor(
  name='StatusCmdStatus',
  full_name='ui.StatusCmdStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='US_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='US_GOOD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='US_UNEXPECTED_CMD', index=2, number=98,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='US_SERVER_EXCEPTION', index=3, number=99,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=439,
  serialized_end=530,
)
_sym_db.RegisterEnumDescriptor(_STATUSCMDSTATUS)

StatusCmdStatus = enum_type_wrapper.EnumTypeWrapper(_STATUSCMDSTATUS)
_UIMODECONTROL = _descriptor.EnumDescriptor(
  name='UiModeControl',
  full_name='ui.UiModeControl',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='C_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='C_SET_MODE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=532,
  serialized_end=575,
)
_sym_db.RegisterEnumDescriptor(_UIMODECONTROL)

UiModeControl = enum_type_wrapper.EnumTypeWrapper(_UIMODECONTROL)
_UIMODESTATUS = _descriptor.EnumDescriptor(
  name='UiModeStatus',
  full_name='ui.UiModeStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CS_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CS_GOOD', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CS_MODE_NA', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CS_MODE_FAIL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CS_UNEXPECTED_CMD', index=4, number=98,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CS_SERVER_EXCEPTION', index=5, number=99,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=577,
  serialized_end=699,
)
_sym_db.RegisterEnumDescriptor(_UIMODESTATUS)

UiModeStatus = enum_type_wrapper.EnumTypeWrapper(_UIMODESTATUS)
U_NONE = 0
U_CNTRL_STATUS = 1
US_NONE = 0
US_GOOD = 1
US_UNEXPECTED_CMD = 98
US_SERVER_EXCEPTION = 99
C_NONE = 0
C_SET_MODE = 1
CS_NONE = 0
CS_GOOD = 1
CS_MODE_NA = 2
CS_MODE_FAIL = 3
CS_UNEXPECTED_CMD = 98
CS_SERVER_EXCEPTION = 99



_CONTROLLERSTATUSCMD = _descriptor.Descriptor(
  name='ControllerStatusCmd',
  full_name='ui.ControllerStatusCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='ui.ControllerStatusCmd.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=61,
)


_CONTROLLERSTATUSRESP = _descriptor.Descriptor(
  name='ControllerStatusResp',
  full_name='ui.ControllerStatusResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ui.ControllerStatusResp.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='ui.ControllerStatusResp.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='ui.ControllerStatusResp.state', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cTime', full_name='ui.ControllerStatusResp.cTime', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='ui.ControllerStatusResp.mode', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='program', full_name='ui.ControllerStatusResp.program', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='ui.ControllerStatusResp.inputs', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='ui.ControllerStatusResp.outputs', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=231,
)


_SETCONTROLLERMODECMD = _descriptor.Descriptor(
  name='SetControllerModeCmd',
  full_name='ui.SetControllerModeCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='ui.SetControllerModeCmd.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reqMode', full_name='ui.SetControllerModeCmd.reqMode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=304,
)


_SETCONTROLLERMODERESP = _descriptor.Descriptor(
  name='SetControllerModeResp',
  full_name='ui.SetControllerModeResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ui.SetControllerModeResp.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='setMode', full_name='ui.SetControllerModeResp.setMode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='ui.SetControllerModeResp.reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=396,
)

_CONTROLLERSTATUSCMD.fields_by_name['cmd'].enum_type = _UICMD
_CONTROLLERSTATUSRESP.fields_by_name['status'].enum_type = _STATUSCMDSTATUS
_SETCONTROLLERMODECMD.fields_by_name['cmd'].enum_type = _UIMODECONTROL
_SETCONTROLLERMODERESP.fields_by_name['status'].enum_type = _UIMODESTATUS
DESCRIPTOR.message_types_by_name['ControllerStatusCmd'] = _CONTROLLERSTATUSCMD
DESCRIPTOR.message_types_by_name['ControllerStatusResp'] = _CONTROLLERSTATUSRESP
DESCRIPTOR.message_types_by_name['SetControllerModeCmd'] = _SETCONTROLLERMODECMD
DESCRIPTOR.message_types_by_name['SetControllerModeResp'] = _SETCONTROLLERMODERESP
DESCRIPTOR.enum_types_by_name['UiCmd'] = _UICMD
DESCRIPTOR.enum_types_by_name['StatusCmdStatus'] = _STATUSCMDSTATUS
DESCRIPTOR.enum_types_by_name['UiModeControl'] = _UIMODECONTROL
DESCRIPTOR.enum_types_by_name['UiModeStatus'] = _UIMODESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControllerStatusCmd = _reflection.GeneratedProtocolMessageType('ControllerStatusCmd', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLLERSTATUSCMD,
  '__module__' : 'ui_pb2'
  # @@protoc_insertion_point(class_scope:ui.ControllerStatusCmd)
  })
_sym_db.RegisterMessage(ControllerStatusCmd)

ControllerStatusResp = _reflection.GeneratedProtocolMessageType('ControllerStatusResp', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLLERSTATUSRESP,
  '__module__' : 'ui_pb2'
  # @@protoc_insertion_point(class_scope:ui.ControllerStatusResp)
  })
_sym_db.RegisterMessage(ControllerStatusResp)

SetControllerModeCmd = _reflection.GeneratedProtocolMessageType('SetControllerModeCmd', (_message.Message,), {
  'DESCRIPTOR' : _SETCONTROLLERMODECMD,
  '__module__' : 'ui_pb2'
  # @@protoc_insertion_point(class_scope:ui.SetControllerModeCmd)
  })
_sym_db.RegisterMessage(SetControllerModeCmd)

SetControllerModeResp = _reflection.GeneratedProtocolMessageType('SetControllerModeResp', (_message.Message,), {
  'DESCRIPTOR' : _SETCONTROLLERMODERESP,
  '__module__' : 'ui_pb2'
  # @@protoc_insertion_point(class_scope:ui.SetControllerModeResp)
  })
_sym_db.RegisterMessage(SetControllerModeResp)



_UIMESSAGES = _descriptor.ServiceDescriptor(
  name='UiMessages',
  full_name='ui.UiMessages',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=701,
  serialized_end=789,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetControllerStatus',
    full_name='ui.UiMessages.GetControllerStatus',
    index=0,
    containing_service=None,
    input_type=_CONTROLLERSTATUSCMD,
    output_type=_CONTROLLERSTATUSRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UIMESSAGES)

DESCRIPTOR.services_by_name['UiMessages'] = _UIMESSAGES


_UICONTROLMODE = _descriptor.ServiceDescriptor(
  name='UiControlMode',
  full_name='ui.UiControlMode',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=791,
  serialized_end=882,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetControllerMode',
    full_name='ui.UiControlMode.SetControllerMode',
    index=0,
    containing_service=None,
    input_type=_SETCONTROLLERMODECMD,
    output_type=_SETCONTROLLERMODERESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UICONTROLMODE)

DESCRIPTOR.services_by_name['UiControlMode'] = _UICONTROLMODE

# @@protoc_insertion_point(module_scope)
